- hosts: k8s-control-plane
  become: yes
  gather_facts: false
  tasks:
  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw

  - name: set join command
    set_fact:
      join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
  - name: HA Control DNS
    lineinfile:
      dest: /etc/hosts
      line: '192.168.63.99 kube-apiserver'
      search_string: 'kube-apiserver'
  - name: join cluster
    shell: "{{ hostvars['k8s-control-plane'].join_command }} --cri-socket=unix:///run/containerd/containerd.sock --ignore-preflight-errors=all >> node_joined.txt"
    args:
      chdir: $HOME
      creates: node_joined.txt