---
  - name: K8s-Common
    hosts: all
    become: yes
    vars:
      apt_k8s_version: 1.24.0-00
      k8s_version: 1.24.0
    tasks:
    # Update apt cache and install required packages
    - name: Update apt cache and install required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - ca-certificates
        - gnupg
        - lsb-release
      become: yes
  
    # Add Docker’s official GPG key
    - name: Add Docker’s official GPG key
      shell: |
              mkdir -p /etc/apt/keyrings
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg
      become: yes
  
    # Add Docker repository
    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu focal stable
        state: present
      become: yes
  
    # Update apt cache
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes
  
    # Enable modules for containerd
    - name: Enable modules for containerd
      modprobe:
        name: "{{ item }}"
        state: present
      with_items:
        - overlay
        - br_netfilter
      become: yes
  
    # Create configuration file to load modules at boot
    - name: Create configuration file to load modules at boot
      copy:
        dest: /etc/modules-load.d/containerd.conf
        content: |
          overlay
          br_netfilter
      become: yes
  
    # Set system configuration for Kubernetes networking
    - name: Set system configuration for Kubernetes networking
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        sysctl_set: yes
        state: present
        reload: yes
      with_dict:
        net.bridge.bridge-nf-call-iptables: 1
        net.bridge.bridge-nf-call-ip6tables: 1
        net.ipv4.ip_forward: 1
      become: yes
  
    # Apply new sysctl settings
    - name: Apply new sysctl settings
      command: sysctl --system
      become: yes
  
    - name: Ensure containerd is installed.
      package:
        name: containerd.io
        state: present

    - name: Ensure containerd is started and enabled at boot.
      service:
        name: containerd
        state: started
        enabled: yes

    - name: Ensure containerd config directory exists.
      file:
        path: /etc/containerd
        state: directory
      register: containerd_dir

    - name: Get defaults from containerd.
      command: containerd config default
      changed_when: false
      register: containerd_config_default

    - name: Prepare containerd/config.toml from default config
      copy:
        dest: /tmp/containerd_config.toml
        content: "{{ containerd_config_default.stdout }}"
      changed_when: false

    - name: Set Cgroup driver to systemd
      lineinfile:
        insertafter: '.*\[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options\]$'
        line: '          SystemdCgroup = true'
        state: present
        path: /tmp/containerd_config.toml
      changed_when: false

    - name: Make sure  SystemdCgroup = false is not set
      ansible.builtin.lineinfile:
        path: /tmp/containerd_config.toml
        state: absent
        line: '            SystemdCgroup = false'
      notify: restart containerd
      changed_when: false

    - name: Copy config.toml to /etc/containerd
      copy:
        remote_src: true
        src: /tmp/containerd_config.toml
        dest: /etc/containerd/config.toml

    - name: Cleanup temporary file
      file:
        path: /tmp/containerd_config.toml
        state: absent
      changed_when: false
  
    # Disable swap
    - name: Disable swap
      command: swapoff -a
      become: yes
  
    # Disable swap in fstab
    - name: Disable swap in fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^/swap.img'
        line: '#/swap.img'
      become: yes
  
    # Download and Install Kubernetes GPG key
    - name: Download and Install Kubernetes GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
      become: yes
  
    # Add Kubernetes repository
    - name: Add Kubernetes repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
      become: yes
  
    # Install Kubernetes packages and set to version  "{{ k8s_version }}"
    - name: Install Kubernetes packages and set to version  "{{ k8s_version }}"
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        allow_downgrade: true
      with_items:
        - "kubelet={{ apt_k8s_version }}"
        - "kubeadm={{ apt_k8s_version }}"
        - "kubectl={{ apt_k8s_version }}"
      become: yes
  
    # Lock Kubernetes packages
    - name: Lock Kubernetes packages
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      with_items:
        - kubelet
        - kubeadm
        - kubectl
      become: yes
  
    # Restart containerd
    - name: Restart containerd
      service:
        name: containerd
        state: restarted
        enabled: yes
      become: yes
  
    # Enable and start kubelet
    - name: Enable and start kubelet
      service:
        name: kubelet
        state: restarted
        enabled: yes
      become: yes
  
